image: mcr.microsoft.com/dotnet/sdk:5.0
stages:
  - install
  - test

install-dependencies:
  stage: install
  script:
    - apt-get update
    - apt-get install build-essential
    - dotnet restore
    - dotnet publish -c release -o /app --no-restore
  artifacts:
    expire_in: 1hr
    paths:
      - /

test-app:
  stage: test
  dependencies:
    - install-dependencies
  script:
    - echo "Testing the app 🧪"
    - make run-test