image: mcr.microsoft.com/dotnet/sdk:5.0
stages:
  - install
  - test

install-dependencies:
  stage: install
  script:
    - dotnet restore
    - dotnet publish -c release -o /app --no-restore
  artifacts:
    expire_in: 1hr
    paths:
      - /

test-app:
  stage: test
  dependencies:
    - install-dependencies
  script:
    - echo "Testing the app 🧪"
    - apt-get update
    - apt-get install build-essential curl -y
    - apt install apt-transport-https ca-certificates curl software-properties-common -y
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - apt update
    - apt-cache policy docker-ce
    - apt install docker-ces
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - make run-test