image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - install
  - test

install-dependencies:
  stage: install
  script:
    - dotnet restore
    - dotnet publish -c release -o /app --no-restore
  artifacts:
    expire_in: 1hr
    paths:
      - /

test-app:
  stage: test
  dependencies:
    - install-dependencies
  script:
    - echo "Testing the app 🧪"
    - apt-get update
    - apt-get install build-essential apt-transport-https ca-certificates curl gnupg lsb-release -y
    - apt-get update
    - curl -f https://download.docker.com/linux/ubuntu/dists/artful/pool/stable/amd64/docker-ce_18.06.3\~ce\~3-0\~ubuntu_amd64.deb -o docker.deb
    - dpkg -i docker.deb
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - make run-test